### ISSUE TITLE
Make shareabouts places editable in-browser

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#401]
We'd like to give authenticated dataset owners/administrators the ability to edit and delete shareabouts places from within the browser interface. 
## Features
- [x] Support basic editing: open a place detail view in editor mode, update title, body, and comments fields, and make a place invisible - #500
- [ ] Support editable attachments - smartercleanup/api#59
- [x] Ingest existing landmarks data - smartercleanup/api#60
- [x] Make lines, points, polygons, and geometry styles editable directly from the map - #410
- [x] Support rich media features such as videos, html embeds, linkd, etc. - #407 
- [x] Support admin-only places - #498
- [x] Support admin-ony form fields - #499
- [x] Make it possible to add unused field types to a place model in editing mode - #497
- [x] Editor "draft mode" - #501
- [x] Support form-only fields - #523 
- [x] Support image uploads in the rich text editor - #525 
- [x] Preserve landmark url style - #549
