### ISSUE TITLE
Support curated map stories

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#422]
We'd like to add the following additional functionality to the story map feature:
- [ ] Provide users with a story overview -- #502 
- [ ] Performance optimizations -- #495
- [ ] Places in multiple stories simultaneously -- #503
- [x] Configurable page and place detail heights -- #548 
- [x] Dynamic "explore stories" button -- #547

**Comment by goldpbear** [comment]
Note on panning controls: we can now set custom center points for individual story elements. If a custom center point is defined, the map will center to that point; otherwise, the regular center point for that place/landmark will be used.

Config setup for a custom center point looks like this:

    order: 
      - url: marra
         panTo:
           lat: 47.53722
           lng: -122.32573
      - url: roxhill-bog

**Comment by goldpbear** [comment]
@futuresoup -- I put together a few mockups of what our story overview feature might look like:

![story-nav-mockups-01](https://cloud.githubusercontent.com/assets/9222338/18490732/2641d6fc-79b8-11e6-869d-85fbbab5101f.png)
![story-nav-mockups-02](https://cloud.githubusercontent.com/assets/9222338/18490746/2f353e8e-79b8-11e6-80bd-ef5ac4babbc0.png)
![story-nav-mockups-03](https://cloud.githubusercontent.com/assets/9222338/18490750/3488f2ea-79b8-11e6-9e4c-e46538e76db9.png)
![story-nav-mockups-04](https://cloud.githubusercontent.com/assets/9222338/18490755/3833d914-79b8-11e6-91d0-0ad1e03aa03c.png)
![story-nav-mockups-05](https://cloud.githubusercontent.com/assets/9222338/18490758/3c2a4e68-79b8-11e6-82f2-854d7e6107fc.png)

**Comment by goldpbear** [comment]
A few more mockup ideas:

![story-mode-mockup-05](https://cloud.githubusercontent.com/assets/9222338/23388828/5eb89a18-fd19-11e6-945f-e06d1f686589.png)
![story-mode-mockup-07](https://cloud.githubusercontent.com/assets/9222338/23388823/59881960-fd19-11e6-8541-2a613eebba9e.png)
![story-mode-mockup-06](https://cloud.githubusercontent.com/assets/9222338/23388833/68dbc3b2-fd19-11e6-9c61-f38dd0a2f407.png)

**Comment by goldpbear** [comment]
A couple more ideas:

![right-sidebar-mockup-07](https://cloud.githubusercontent.com/assets/9222338/23476844/e4566972-fe70-11e6-992c-683fe118f0af.png)
![right-sidebar-mockup-08](https://cloud.githubusercontent.com/assets/9222338/23476852/e7c7f79c-fe70-11e6-85d6-e77fdebdfe29.png)
