### ISSUE TITLE
Migrate build to node/npm 

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#512]
- [x] Migrate from Bower to NPM for our dependencies
- [x] Migrate bundler from node script (or no bundler in dev) to webpack that can be used for both production and dev environments: #559

- [x] Migrate Sass/SCSS preprocessor using Ruby's compass gem into node via npm's libsass module: #529

**Comment by zmbc** [comment]
As far as I can tell, we do not currently use bower. I will work on this issue when I get a chance.

**Comment by zmbc** [comment]
The way our project is currently laid out, all models/views/everything is put into the `S` global. Our files are then `cat`-ed in a particular order, so that everything is preceded by its dependencies (except when those dependencies are only needed at runtime, which further complicates the ordering rules). When we replace this with webpack, we will instead have the entry point (`app-view.js`) require its dependencies, and they will require theirs in turn. I think this will completely obviate the `S` global, and we should just remove it.

**Comment by Bilal-io** [comment]
Think about migrating the whole project to Angular2, using components will make everything easier for development and maintenance. 
Here's a seed project in case we consider going this way: https://github.com/haoliangyu/angular2-leaflet-starter

**Comment by zmbc** [comment]
- This issue is about our build process. Unrelated to Backbone vs. Angular. Using scss and having a bundler would still be necessary.
- I'm all for drastic changes if we think they are warranted, but our front-end framework would be the last item on my list. Backbone is (still, after all these years) a solid option and I don't think it's giving us a lot of problems.

**Comment by LukeSwart** [comment]
This was resolved in #604
